apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mongo-express
  labels:
    name: mongo-express
spec:
  rules:
  - host: myapp.com
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: mongo-express-service
            port: 
              number: 8081
